name: OWASP ZAP security testing

on: 
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e 
        with:
          node-version: 16
      
      - name: Install CLI tools
        run: npm install -g @angular/cli@$ANGULAR_CLI_VERSION

      - name: Install application minimalistically
        run: |
          npm install --ignore-scripts
          cd frontend
          npm install --ignore-scripts --legacy-peer-deps

      - name: Lint source code
        run: npm run lint

      - name: Lint customization configs
        run: >
          npm run lint:config -- -f ./config/7ms.yml &&
          npm run lint:config -- -f ./config/addo.yml &&
          npm run lint:config -- -f ./config/bodgeit.yml &&
          npm run lint:config -- -f ./config/ctf.yml &&
          npm run lint:config -- -f ./config/default.yml &&
          npm run lint:config -- -f ./config/fbctf.yml &&
          npm run lint:config -- -f ./config/juicebox.yml &&
          npm run lint:config -- -f ./config/mozilla.yml &&
          npm run lint:config -- -f ./config/oss.yml &&
          npm run lint:config -- -f ./config/quiet.yml &&
          npm run lint:config -- -f ./config/tutorial.yml &&
          npm run lint:config -- -f ./config/unsafe.yml
      
      - name: Run OWASP ZAP Scan
        run: |
          sudo apt-get update
          sudo apt-get install zaproxy -y

      - name: Run OWASP ZAP Active Scan on Login
        run: |
          zap-full-scan.py -t http://localhost:4200/#/login -r zap_login_scan_report.html

      
      - name: Run OWASP ZAP Active Scan on Search
        run: |
          zap-full-scan.py -t 'http://localhost:4200/#/search?q=orange' -r zap_search_scan_report.html
      
      
      - name: Upload OWASP ZAP Reports
        uses: actions/upload-artifact@v2
        with:
          name: zap-reports
          path: |
            zap_report.html
            zap_login_scan_report.html
            zap_search_scan_report.html